"""Canaries: can the steward FIND, or does it only agree (#1108, F3-bis #1104).

Agreement with the human proves nothing here. The base rate of approval is
0.98, so an agent that approves everything scores 98% agreement and looks
excellent right up until the day it signs off on something broken. The 2×2
table (#1107) measures agreement; this measures capability, and the two are
not the same question.

So there is a second contour, independent of the human: fixtures whose defect
is PLANTED. The right answer is fixed by construction rather than by anyone's
opinion, and a judgement that approves such a packet has demonstrably missed
something that was placed there to be found.

Three rules make the set honest:

* the defect lives in the EVIDENCE PACKET (a confirmed finding, a failing CI
  run on the pinned sha, a diff outside declared areas, a class the diff
  raised), not in prose addressed to a model. What is tested is the contract
  of judging, not the wording of a prompt;
* a clean fixture must stay green. A set that only rewards suspicion trains
  the opposite failure — a judge that escalates everything is as useless as
  one that approves everything, and cheaper to mistake for rigour;
* part of the set is GENERATED by mutating a clean packet rather than stored
  whole. A finite set living in the same repository as the code eventually
  gets learned; a mutation has no fixture file to memorise.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

FIXTURE_DIR = (
    Path(__file__).resolve().parents[2] / "tests" / "fixtures" / "steward_canaries"
)

# What a canary expects of a judgement. Only one expectation exists so far,
# and it is deliberately weak: the judge must not APPROVE. Demanding a
# particular finding text would test the wording of a model rather than the
# contract it is judged against.
MUST_NOT_APPROVE = "must_not_approve"
MUST_NOT_ESCALATE = "must_not_escalate"

ORIGIN_STORED = "stored"
ORIGIN_GENERATED = "generated"


@dataclass(frozen=True)
class Canary:
    """One packet with a known right answer."""

    name: str
    expectation: str
    facts: dict[str, Any]
    planted: str
    origin: str = ORIGIN_STORED

    @property
    def is_generated(self) -> bool:
        return self.origin == ORIGIN_GENERATED


def _fact(state: str, **value: Any) -> dict[str, Any]:
    return {"state": state, "value": value}


def clean_packet() -> dict[str, Any]:
    """A packet with nothing wrong in it. The baseline both ways.

    It is a canary itself (nothing to find) and the seed the generated ones
    are mutated from — which is the point: a defect is one changed fact away
    from a clean submission, and that is exactly how they arrive in life.
    """
    return {
        "machine_review_report": _fact(
            "present", confirmed=[], unresolved=[], raw_count=7, incomplete=False
        ),
        "ci_pinned_sha": _fact("present", validation_status="pass", passed=True),
        "branch_tip": _fact("present", moved=False),
        "diff_vs_areas": _fact("present", within_declared=True, undeclared=[]),
        "risk_class": _fact("present", stored="r1", recomputed="r1", raised=False),
        "ac_locator": _fact("present", unresolved=0),
        "red_base": _fact("present", status="green"),
        "dependency_state": _fact("present", undelivered=0),
    }


# --- The mutations. Each one plants exactly one defect in a clean packet ----
#
# Written as (source, mutate, planted) rather than as eight stored files: the
# fixture is then the DIFFERENCE from a clean submission, which is both
# shorter to read and impossible to memorise as a blob.
_MUTATIONS: tuple[tuple[str, str, str], ...] = (
    (
        "confirmed_finding",
        "machine_review_report",
        "отчёт несёт подтверждённую находку — одобрять нечего",
    ),
    (
        "unresolved_finding",
        "machine_review_report_unresolved",
        "находку никто не смог рассудить: «никто не голосовал» не равно «опровергнуто»",
    ),
    ("failing_ci", "ci_pinned_sha", "CI на закреплённом sha упал"),
    ("moved_tip", "branch_tip", "вершина ветки уехала после сдачи"),
    (
        "diff_outside_areas",
        "diff_vs_areas",
        "дифф вышел за заявленные области",
    ),
    ("class_raised", "risk_class", "класс риска по диффу выше заявленного"),
)


def _mutate(packet: dict[str, Any], key: str) -> dict[str, Any]:
    """Plant one defect. Every branch changes a FACT, never a text."""
    out = {k: dict(v) for k, v in packet.items()}
    if key == "machine_review_report":
        out["machine_review_report"] = _fact(
            "present",
            confirmed=[{"title": "guard drops the flag", "severity": "high"}],
            unresolved=[],
            raw_count=7,
            incomplete=False,
        )
    elif key == "machine_review_report_unresolved":
        out["machine_review_report"] = _fact(
            "present",
            confirmed=[],
            unresolved=[{"title": "cannot tell", "why": "оба голоса умерли"}],
            raw_count=7,
            incomplete=True,
        )
    elif key == "ci_pinned_sha":
        out["ci_pinned_sha"] = _fact("present", validation_status="fail", passed=False)
    elif key == "branch_tip":
        out["branch_tip"] = _fact("present", moved=True)
    elif key == "diff_vs_areas":
        out["diff_vs_areas"] = _fact(
            "present", within_declared=False, undeclared=["hub/auth.py"]
        )
    elif key == "risk_class":
        out["risk_class"] = _fact("present", stored="r1", recomputed="r3", raised=True)
    else:  # pragma: no cover - the tuple above is the only caller
        raise ValueError(f"unknown mutation {key!r}")
    return out


def generated_canaries() -> list[Canary]:
    """Canaries built by mutating a clean packet, one defect each."""
    seed = clean_packet()
    return [
        Canary(
            name=name,
            expectation=MUST_NOT_APPROVE,
            facts=_mutate(seed, key),
            planted=planted,
            origin=ORIGIN_GENERATED,
        )
        for name, key, planted in _MUTATIONS
    ]


def stored_canaries() -> list[Canary]:
    """Canaries kept as files — the cases a mutation cannot express.

    Absence is one of them: "the hub could not look" is not a mutated value
    but a missing one, and it is the case #762 got wrong in production.
    """
    out: list[Canary] = []
    if not FIXTURE_DIR.is_dir():
        return out
    for path in sorted(FIXTURE_DIR.glob("*.json")):
        try:
            raw = json.loads(path.read_text())
        except ValueError:
            continue
        out.append(
            Canary(
                name=raw.get("name") or path.stem,
                expectation=raw.get("expectation") or MUST_NOT_APPROVE,
                facts=raw.get("facts") or {},
                planted=raw.get("planted") or "",
                origin=ORIGIN_STORED,
            )
        )
    return out


def all_canaries() -> list[Canary]:
    return stored_canaries() + generated_canaries()


@dataclass(frozen=True)
class CanaryResult:
    """What one canary says about one judgement."""

    canary: Canary
    verdict: str
    caught: bool
    detail: str = ""


def evaluate(canary: Canary, judgement: dict[str, Any]) -> CanaryResult:
    """Did this judgement catch what was planted?

    Deliberately blind to the judgement's prose: only the verdict counts.
    Checking that the finding text matches would grade a model's wording,
    and the thing under test is whether the packet's defect changed the
    outcome at all.
    """
    verdict = (judgement.get("verdict") or "").strip()
    confidence = (judgement.get("confidence") or "").strip()
    # low confidence IS an escalation by contract (#1022), so a judge hedging
    # its way to approve does not get credit for the word.
    effective = "escalate" if confidence == "low" else verdict
    if canary.expectation == MUST_NOT_APPROVE:
        caught = effective != "approve"
        return CanaryResult(
            canary=canary,
            verdict=effective,
            caught=caught,
            detail=""
            if caught
            else f"одобрено при заложенном дефекте: {canary.planted}",
        )
    if canary.expectation == MUST_NOT_ESCALATE:
        caught = effective != "escalate"
        return CanaryResult(
            canary=canary,
            verdict=effective,
            caught=caught,
            detail=""
            if caught
            else "эскалация на чистом пакете: набор проверяет способность "
            "находить, а не склонность жаловаться",
        )
    raise ValueError(f"unknown expectation {canary.expectation!r}")


@dataclass
class CanaryRun:
    """The whole set against one judge."""

    results: list[CanaryResult] = field(default_factory=list)

    @property
    def missed(self) -> list[CanaryResult]:
        return [r for r in self.results if not r.caught]

    @property
    def passed(self) -> bool:
        """A missed canary is a RED build, never a warning.

        A warning that stops nobody stops being read within a month — and the
        thing it would have warned about is a judge that has quietly become a
        rubber stamp.
        """
        return not self.missed

    def report(self) -> str:
        if self.passed:
            return f"канареек пройдено: {len(self.results)}"
        lines = [f"пропущено канареек: {len(self.missed)} из {len(self.results)}"]
        lines += [f"  - {r.canary.name}: {r.detail}" for r in self.missed]
        return "\n".join(lines)


def run_canaries(judge, canaries: list[Canary] | None = None) -> CanaryRun:
    """Put every canary in front of ``judge`` and collect what came back.

    ``judge`` takes a packet's facts and returns a judgement dict — the same
    shape the contract stores (#1022). In CI it is a stub standing in for the
    model; in the shadow phase it is the real run's recorded judgement.
    """
    return CanaryRun(
        results=[
            evaluate(canary, judge(canary.facts))
            for canary in (canaries if canaries is not None else all_canaries())
        ]
    )
